excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://havashop91.github.io
title: M&#7929; ph&#7849;m xách tay chính h&#227;ng HAVAShop
email: havashop91@gmail.com
author: HAVA Shop
description: Chuyên cung c&#7845;p m&#7929; ph&#7849;m xách tay chính h&#227;ng, th&#7921;c ph&#7849;m ch&#7913;c nãng xách tay chính h&#227;ng 100% t&#7915; M&#7929;, Pháp, Hàn Qu&#7889;c,...
paginate: 10
google_analytics: 